CREATE OR REPLACE TRIGGER INSERT_AND_UPDATE 
AFTER INSERT ON PAGO
FOR EACH ROW
DECLARE
CURSOR CURCargoEstudiante IS
SELECT CARNE, MONTO, SALDO, FECHA_VENCIMIENTO, DESCRIPCION 
FROM CARGO 
WHERE CARNE = (:NEW.CARNE)
ORDER BY FECHA_VENCIMIENTO ASC;
--FIN DECLARE

BEGIN
DBMS_OUTPUT.put_line ('   CARNE   |   MONTO');
FOR Iteracion IN CURCargoEstudiante
LOOP
 DBMS_OUTPUT.put_line (Iteracion.CARNE ||'   |   '|| Iteracion.MONTO);
END LOOP;
  NULL;
END;